### ISSUE TITLE
validation errors

### ISSUE THREAD

**Issue by tigrazone** [spnda/vk_gltf_viewer#2]
spnda-vk_gltf_viewer\build>vk_gltf_viewer c:\temp\glTF-Sample-Assets\Models\ABeautifulGame\glTF\ABeautifulGame.gltf
Successfully created ImGui pipeline cache
Validation Error: [ VUID-VkViewport-width-01770 ] Object 0: handle = 0x22b73d3c420, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa4164ba5 | vkCmdSetViewport(): pViewports[0].width (0.000000) is not greater than 0.0. The Vulkan spec states: width must be greater than 0.0 (https://vulkan.lunarg.com/doc/view/1.3.275.0/windows/1.3-extensions/vkspec.html#VUID-VkViewport-width-01770)

Windows 10
Compiler Visual Studio 2019

Sometimes I have more errors when import another gltfs

**Comment by tigrazone** [comment]
spnda-vk_gltf_viewer\build>vk_gltf_viewer.exe c:\temp\glTF-Sample-Assets\Models\ToyCar\gltf\ToyCar.gltf
Successfully created ImGui pipeline cache
Validation Error: [ VUID-VkViewport-width-01770 ] Object 0: handle = 0x175579c4ee0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa4164ba5 | vkCmdSetViewport(): pViewports[0].width (0.000000) is not greater than 0.0. The Vulkan spec states: width must be greater than 0.0 (https://vulkan.lunarg.com/doc/view/1.3.275.0/windows/1.3-extensions/vkspec.html#VUID-VkViewport-width-01770)
Validation Error: [ VUID-VkViewport-width-01770 ] Object 0: handle = 0x175579c66e0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa4164ba5 | vkCmdSetViewport(): pViewports[0].width (0.000000) is not greater than 0.0. The Vulkan spec states: width must be greater than 0.0 (https://vulkan.lunarg.com/doc/view/1.3.275.0/windows/1.3-extensions/vkspec.html#VUID-VkViewport-width-01770)
Validation Error: [ VUID-VkViewport-width-01770 ] Object 0: handle = 0x175579c4ee0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa4164ba5 | vkCmdSetViewport(): pViewports[0].width (0.000000) is not greater than 0.0. The Vulkan spec states: width must be greater than 0.0 (https://vulkan.lunarg.com/doc/view/1.3.275.0/windows/1.3-extensions/vkspec.html#VUID-VkViewport-width-01770)
Validation Error: [ VUID-vkDestroyImage-image-01000 ] | MessageID = 0xf2d29b5a | vkDestroyImage():  can't be called on VkImage 0x74d977000000004a[] that is currently in use by VkCommandBuffer 0x175579c66e0[]. The Vulkan spec states: All submitted commands that refer to image, either directly or via a VkImageView, must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.275.0/windows/1.3-extensions/vkspec.html#VUID-vkDestroyImage-image-01000)
Validation Error: [ VUID-vkDestroyDevice-device-05137 ] Object 0: handle = 0x69eeaa0000000047, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4872eaa0 | vkCreateDevice():  OBJ ERROR : For VkDevice 0x175524c7f80[], VkImageView 0x69eeaa0000000047[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.3.275.0/windows/1.3-extensions/vkspec.html#VUID-vkDestroyDevice-device-05137)
Validation Error: [ VUID-vkDestroyDevice-device-05137 ] Object 0: handle = 0x7323f50000000048, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4872eaa0 | vkCreateDevice():  OBJ ERROR : For VkDevice 0x175524c7f80[], VkImageView 0x7323f50000000048[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.3.275.0/windows/1.3-extensions/vkspec.html#VUID-vkDestroyDevice-device-05137)
Validation Error: [ VUID-vkDestroyDevice-device-05137 ] Object 0: handle = 0x40b43c0000000049, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4872eaa0 | vkCreateDevice():  OBJ ERROR : For VkDevice 0x175524c7f80[], VkImageView 0x40b43c0000000049[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.3.275.0/windows/1.3-extensions/vkspec.html#VUID-vkDestroyDevice-device-05137)

Errors fired when I do window resize and close window for execution of program

**Comment by spnda** [comment]
Does the `vkCmdSetViewport` thing still come up? I've fixed all the other image view and swapchain sync errors.

**Comment by tigrazone** [comment]
No. Issue is fixed
