### ISSUE TITLE
Something strange with textures

### ISSUE THREAD

**Issue by tigrazone** [spnda/vk_gltf_viewer#6]
scene glTF-Sample-Assets\Models\ToyCar\glTF-Binary\ToyCar.glb
![image](https://github.com/spnda/vk_gltf_viewer/assets/3808839/3d01e535-3037-43ee-ac7d-1e0f8702a16c)
![image](https://github.com/spnda/vk_gltf_viewer/assets/3808839/4efeb25e-4911-4688-983c-13ad37e0e658)
![image](https://github.com/spnda/vk_gltf_viewer/assets/3808839/0b458740-36b9-4b25-9d72-fedde51e9243)

scene glTF-Sample-Assets\Models\ABeautifulGame\glTF\ABeautifulGame.gltf
![image](https://github.com/spnda/vk_gltf_viewer/assets/3808839/ff2d6a3b-b7c0-442c-9ea9-d3dbeadd2a3c)
![image](https://github.com/spnda/vk_gltf_viewer/assets/3808839/0e35f84e-dbc2-4668-bd07-40e9d9df43bd)

maybe take a look at N/A Variant

**Comment by spnda** [comment]
Yes I already fixed this locally, probably.

https://github.com/spnda/vk_gltf_viewer/blob/50520eafc33a973ee7dec96b0bfa7d3143c01ce8/src/main.cpp#L2312

I accidentally used has_value() instead of value() here, which broke uncompressed textures.

**Comment by tigrazone** [comment]
Funny typo ;-)

**Comment by spnda** [comment]
Fixed with 6025254d65fc1f981ca2313bb07b5dbf4afb5d76.
