### ISSUE TITLE
vk_gltf_viewer doesnt build in Visual Studio 2022

### ISSUE THREAD

**Issue by tigrazone** [spnda/vk_gltf_viewer#7]
![image](https://github.com/user-attachments/assets/28ea3c16-2f6d-4aae-9e34-d858d96380bf)

**Comment by spnda** [comment]
I've updated the fastgltf submodule and we had some [recent changes](https://github.com/spnda/fastgltf/commit/c462eaf7114f16a977afe84d0a4590b33091a33f) in fastgltf about those monadic operators on optionals.

I think the submodule was just outdated for you, but this should definitely build. I'll close this now.

**Comment by tigrazone** [comment]
same error
![image](https://github.com/user-attachments/assets/71eb8545-292f-4c3f-a019-e72f1a71988d)
